# Generated by Django 6.1 on 2026-08-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_bookvote"),
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to="books.book",
            ),
        ),
    ]
